// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2WYrR3xjSg4Vpd_CFTlrho33oPwpKxeI',
    appId: '1:759460043840:web:3ada234dea532203e993a5',
    messagingSenderId: '759460043840',
    projectId: 'subtle-striker-424805-e3',
    authDomain: 'subtle-striker-424805-e3.firebaseapp.com',
    storageBucket: 'subtle-striker-424805-e3.appspot.com',
    measurementId: 'G-F8PLP6GCTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFY9bZrVMiAkn1-y197PYvvM-_zUmomAY',
    appId: '1:759460043840:android:296a326578879f2fe993a5',
    messagingSenderId: '759460043840',
    projectId: 'subtle-striker-424805-e3',
    storageBucket: 'subtle-striker-424805-e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3qoBizbFJvr1hn-r5AKsP9IYb_1iop00',
    appId: '1:759460043840:ios:a2037a4370e9f35ce993a5',
    messagingSenderId: '759460043840',
    projectId: 'subtle-striker-424805-e3',
    storageBucket: 'subtle-striker-424805-e3.appspot.com',
    iosBundleId: 'com.halflambda.aigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3qoBizbFJvr1hn-r5AKsP9IYb_1iop00',
    appId: '1:759460043840:ios:a2037a4370e9f35ce993a5',
    messagingSenderId: '759460043840',
    projectId: 'subtle-striker-424805-e3',
    storageBucket: 'subtle-striker-424805-e3.appspot.com',
    iosBundleId: 'com.halflambda.aigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2WYrR3xjSg4Vpd_CFTlrho33oPwpKxeI',
    appId: '1:759460043840:web:8faa042585fcd9a8e993a5',
    messagingSenderId: '759460043840',
    projectId: 'subtle-striker-424805-e3',
    authDomain: 'subtle-striker-424805-e3.firebaseapp.com',
    storageBucket: 'subtle-striker-424805-e3.appspot.com',
    measurementId: 'G-B1WKQLXJ3S',
  );

}